### ISSUE TITLE
airdraw client cannot find any canvas

### ISSUE THREAD

**Issue by kinwahlai** [threeMF/threeMF#3]
Hi,

i built the airdraw client on my iphone and airdraw host on my mac, however client just can't locate any canvas. both devices are on the same wifi network. 
Anything i did wrong that makes it not working? 

cheers,
kinwah

**Comment by mgratzer** [comment]
Being on the same network and tapping the screen on the iPhone once should be sufficient to open the canvas browser listing available hosts. You have to make sure that your network is not blocking "random" ports and allows Bonjour. 

You could try to switch the constant TMFLogLevel to TMF_LOG_LEVEL_INFO in TMFLog.h. The system should start giving you some more information in your console.

**Comment by kinwahlai** [comment]
i can locate the canvas and draw after i enable the bonjour support in my router. Thank you for the reply.
