### ISSUE TITLE
Publish/Subscribe Example - Wrong Signature on subscribe:

### ISSUE THREAD

**Issue by semireg** [threeMF/threeMF#6]
Current documentation reads:

receive:^(TMFKeyValueCommandArguments *arguments){
                 // do awesome things
                 NSLog(@"%@: %@", arguments.key, arguments.value);
            }

... should be:

```
             receive:(pubSubArgumentsReceivedBlock_t)^(TMFKeyValueCommandArguments *arguments, TMFPeer *peer)
             {
                 NSLog(@"Reading Network Data - %@: %@", arguments.key, arguments.value);
             }
```

There is another minor typo...

Currently reads:
                 [self.tmf subscribe:[TMFKeyValueCommand name]

... should be:

```
    [self.tmf subscribe:[TMFKeyValueCommand class]
```

**Comment by mgratzer** [comment]
Thank you @caylanlarson! These changes where added last minute, totally missed to fix the documentation.
